version: '3.8'

services:
  container:
    build:
      context: ./container
    ports:
      - "3000:80"

  header-app:
    build:
      context: ./header-app
    ports:
      - "3001:80"

  product-app:
    build:
      context: ./product-app
    ports:
      - "3002:80"

  cart-app:
    build:
      context: ./cart-app
    ports:
      - "3003:80"

  admin-app:
    build:
      context: ./admin-app
    ports:
      - "3004:80"

  store-app:
    build:
      context: ./store-app
    ports:
      - "3005:80"

  design-system-app:
    build:
      context: ./design-system-app
    ports:
      - "3006:80"

  # THÊM MỚI 2 CORE BACKEND LÕI:
  backend-api:
    build:
      context: ./backend-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/stuffy_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
