# Specific values for GraphQL Gateway (BFF)
replicaCount: 2

image:
  repository: stuffy-supermarket/graphql-gateway
  tag: latest

service:
  port: 4000

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  PORT: "4000"
  NODE_ENV: "production"
  # URL must point to the backend-api-service within the cluster
  SUBGRAPH_PRODUCTS_URL: "http://backend-api-service:80/graphql"

probe:
  path: "/graphql"
