# Specific values for MongoDB deployment
# Typically used with a separate official chart, but we simplify for demo
replicaCount: 1

image:
  repository: mongo
  tag: latest

service:
  port: 27017

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false # Databases usually don't use HPA at this level

env:
  MONGO_INITDB_DATABASE: "stuffy_db"

probe:
  # Mongo is binary, but we use a non-standard probe or TCP
  path: "/"
